### ISSUE TITLE
Help with accessing app through browser, container id questions, inter alia

### ISSUE THREAD

**Issue by youanden** [zehnergroup/cheesy-poofs#3]
This is the result of my `docker ps` after having done a `vagrant up --no-parallel` following a `vagrant destroy`
```
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                                                                              NAMES
3baa83bf99e8        c568c4be8def        "/start.sh"         8 minutes ago       Up 8 minutes        443/tcp, 0.0.0.0:8999->80/tcp                                                      cheesy-poofs_nginx_1438808655
cd17b87042d9        66edb3720f49        "./bin/start.sh"    9 minutes ago       Up 9 minutes        0.0.0.0:5354->5354/tcp, 0.0.0.0:8004->8004/tcp, 0.0.0.0:8384->8384/tcp, 8003/tcp   cp-frontend
```

I can't seem to proceed in following the instructions laid out. Specifically, I don't see the image named `zehnergroup/zg-site:latest` - however, I was able to easily bash into both containers in the next step.

The problem for me seems to be that I do not know how to access the deployed applications.

For example, my hosts has the following lines:
```
127.0.0.1 boot2docker
192.168.100.200 docker.local
```

Although when I run a command like:
`docker inspect --format '{{ .NetworkSettings.IPAddress }}' cd17b87042d9`

I get a different IP than either of those listed in my hosts file. Is there something I can do to access the deployed application via http?

**Comment by duro** [comment]
The README has the link to pull up the app in the browser:

https://github.com/zehnergroup/cheesy-poofs#access-app

Basically, go to: http://docker.local:8004

**Comment by duro** [comment]
Also, the container that matters is the one named `cp-frontend`. So it's the container ID for that container that you should use when running other docker commands, like `docker exec`

**Comment by youanden** [comment]
@duro Well that was quick!

I guess I missed that and instead tried to access `http://docker.local:8383/debug?ws=docker.local:8384&port=5354` - is this supposed to work out of the box or should there be more configuration?

**Comment by duro** [comment]
That is the URL for the debugger, which should work out of the box.

The app is basically a boilerplate, it gives you a starter, and then you extend from there.

**Comment by youanden** [comment]
Can I debug why the debugger isn't working? I'm getting a connection refused.

EDIT: `http://docker.local:8384/debug?ws=docker.local:8384&port=5354` works
`http://docker.local:8383/debug?ws=docker.local:8384&port=5354` doesn't

Maybe need to update README.txt?

**Comment by duro** [comment]
Updating README

**Comment by youanden** [comment]
Thanks so much for the help!

**Comment by duro** [comment]
Fixed. Also, I updated node-debugger to the lastest version. If you do a fresh pull, then `vagrant reload` you should get the update.

**Comment by youanden** [comment]
@duro Awesome, looks like server-side breaks are working now in the debugger (though it may have just been negligence on my part).
