### ISSUE TITLE
Add space to import statement in test.js

### ISSUE THREAD

**Issue by youanden** [zehnergroup/cheesy-poofs#4]
https://github.com/zehnergroup/cheesy-poofs/blob/a22943806ada29e9b6f4a47d492f874a5c788c51/src/server/api/test.js#L6

@duro Would you prefer I sent a patch for something like this or just create an issue?

**Comment by duro** [comment]
PRs are your path to fame, glory and profit! Fire away. No PR is too small.

**Comment by duro** [comment]
BTW, that import is totally unnecessary. You can delete it all together. It is junk left over from me stripping the boilerplate out of it's parent project.

**Comment by youanden** [comment]
@duro Whoops, haha. Missed that message by a minute.
